// <auto-generated>
// Generated from the CaseNo and ClaimNo columns of the SharePoint "Matters Lookup" list
// (site: MatterExchange-POC). Patterns are generalized by structural shape rather than
// literal carrier/court prefix, so a single pattern covers many distinct prefixes.
// 10 patterns cover 1645 of 1648 distinct observed values (99.8%).
// Known uncovered outliers (likely data-entry typos):
//   "00144258D" (numeric id with trailing letter, single occurrence)
//   "25-99-798924" (irregular shape, single occurrence)
//   "34-2022-00328746" (looks like a long-form case no missing its -XX-XXX-XXX suffix)
// </auto-generated>

namespace RegExAzFunc
{
    public static class CaseClaimNoPatterns
    {
        public static readonly string[] Patterns =
        {
            // CA short-form case no: 25STCV28299, 2025CUPA060925, 25CU065314C, 1SZ0085
            @"^\d{1,4}[A-Z]{2,5}-?\d{3,6}[A-Z]?$",

            // CA long-form / unlimited civil case no: 30-2023-01351580-CU-PO-NJC, 37-2024-900089-CU-PA-CTL
            @"^\d{2}-\d{4}-\d{6,8}-[A-Z]{2}-[A-Z]{2,3}-?[A-Z]{2,3}$",

            // Letter-prefixed claim/case ids: BEAZL100006002890, CABP-00002738, GRBP213585-001-001-001, KBAMG24010279, AB949-433804-01, CGC-24-619639
            @"^[A-Z]{1,5}-?\d{2,12}(-\d{2,7}){0,3}(-[A-Z]{1,3})?$",

            // STK tracking id: STK-CV-UAT-2025-0006542
            @"^STK-CV-[A-Z]{2,4}-\d{4}-\d{4,8}$",

            // Federal district court case no: 2:23cv1881, 8:23-cv-01261-JWH-DFM
            @"^\d:\d{2}-?[Cc][Vv]-?\d{4,6}(-[A-Z]{2,4}(-[A-Z]{2,4})?)?$",

            // Plain numeric claim id: 21000036612, 0187056, 7009474546-1, 297739
            @"^\d{6,11}(-\d{1,3})?$",

            // 6-digit + 2-letter claim suffix: 788263-GQ, 117306GQ
            @"^\d{6}-?[A-Z]{2}$",

            // Dated claim id: 1106-AL-24-0300093
            @"^\d{4}-[A-Z]{2}-\d{2}-\d{7}(\s?[A-Z]{2,3})?$",

            // Dash-separated claim no: 23-4226358, 24-216011247, 36508-0046, 40137-0124
            @"^\d{2,5}-\d{4,9}$",

            // Code-segment id: 25-CIV-07139, S-CV-0056835
            @"^[A-Z0-9]{1,2}-[A-Z]{2,4}-\d{5,8}$",
        };
    }
}
