// <auto-generated>
// Generated from the RSEFileNo column of the SharePoint "Matters Lookup" list
// (site: MatterExchange-POC). 1 pattern covers 1038 of 1041 distinct observed values (99.7%).
// Known uncovered outliers:
//   "UnsortedMatterCommunication" — this is the app's own unclassified-matter placeholder
//     string (see RegExMattersAzFunc.cs / UnsortedMattersByRegEx.cs), not a real file number;
//     it appears to have been written back into the RSEFileNo field.
//   "1090007" (plain 7-digit number, no dot, single occurrence — likely a typo)
//   "99.072." (trailing stray period, single occurrence — likely a typo)
// </auto-generated>

namespace RegExAzFunc
{
    public static class RSEFileNoPatterns
    {
        public static readonly string[] Patterns =
        {
            // RSE File No: 06.092, 100.205, 130.035B, 95A.101, 25.0012
            @"^\d{2,3}[A-Z]?\.\d{3,4}[A-Z]?$",
        };
    }
}
