// <auto-generated>
// Generated from the RSEFileNo column of the SharePoint "Matters Lookup" list
// (site: MatterExchange-POC). Regenerated 2026-08-19 after Matters-Lookup-Sync backfilled
// 273 matters from the intake spreadsheet. 1 pattern covers 1310 of 1313 distinct observed
// values (99.8%) - the 273 additions introduced no new file-number shape, so the pattern is
// unchanged and only the counts and the outlier list below moved.
// Known uncovered outliers:
//   "UnsortedMatterCommunication" — this is the app's own unclassified-matter placeholder
//     string (see RegExMattersAzFunc.cs / UnsortedMattersByRegEx.cs), not a real file number;
//     it appears to have been written back into the RSEFileNo field.
//   "1090007" (plain 7-digit number, no dot, single occurrence — likely a typo)
//   "99.072." (trailing stray period, single occurrence — likely a typo)
//
// "113.01" was a fourth outlier and is no longer: it was a mistyped "113.001" in the intake
// spreadsheet. Confirmed rather than assumed - matters/113.001/ in the archive holds 203
// emails naming the same parties as that sheet row (Goloborodko v. Labh Sing, CSAA claim
// 25-99-798924), and nothing had ever been filed under 113.01. The cell was corrected and
// the lookup row the backfill had created from the typo was deleted. Recorded here because
// the obvious "fix" - widening the tail to \d{2,4} - would have matched the typo while
// destroying the pattern's ability to tell a real file number from a truncated one.
// </auto-generated>

namespace RegExAzFunc
{
    public static class RSEFileNoPatterns
    {
        public static readonly string[] Patterns =
        {
            // RSE File No: 06.092, 100.205, 130.035B, 95A.101, 25.0012
            @"^\d{2,3}[A-Z]?\.\d{3,4}[A-Z]?$",
        };
    }
}
