// <auto-generated>
// Generated from the RSEFileNo column of the SharePoint "Matters Lookup" list
// (site: MatterExchange-POC). Regenerated 2026-08-19 after Matters-Lookup-Sync backfilled
// 273 matters from the intake spreadsheet. 1 pattern covers 1310 of 1314 distinct observed
// values (99.7%) - the 273 additions introduced no new file-number shape, so the pattern is
// unchanged and only the counts and the outlier list below moved.
// Known uncovered outliers:
//   "UnsortedMatterCommunication" — this is the app's own unclassified-matter placeholder
//     string (see RegExMattersAzFunc.cs / UnsortedMattersByRegEx.cs), not a real file number;
//     it appears to have been written back into the RSEFileNo field.
//   "1090007" (plain 7-digit number, no dot, single occurrence — likely a typo)
//   "99.072." (trailing stray period, single occurrence — likely a typo)
//   "113.01" (two-digit tail; the list also holds "113.001", so this is almost certainly the
//     same matter mistyped in the intake spreadsheet. Left uncovered deliberately: widening
//     the tail to \d{2,4} would match it, but it would also stop the pattern distinguishing
//     a real file number from a truncated one. Fix the spreadsheet cell instead.)
// </auto-generated>

namespace RegExAzFunc
{
    public static class RSEFileNoPatterns
    {
        public static readonly string[] Patterns =
        {
            // RSE File No: 06.092, 100.205, 130.035B, 95A.101, 25.0012
            @"^\d{2,3}[A-Z]?\.\d{3,4}[A-Z]?$",
        };
    }
}
