using Company.Function;

namespace RegExAzFunc.Tests;

/// <summary>
/// The C# token must equal what ingest-key.py produced, because 401,170 blob names already
/// encode the Python function's output. These triples were generated by that function.
/// </summary>
public class DedupTokenConformanceTests
{
    public static TheoryData<string, string, string> Reference => new()
    {
        // Generated by ingest-key.py's dedup_key(mid, sent) on 2026-09-08. Do not edit by
        // hand: if C# disagrees with a row, the C# is wrong, because these are what named
        // 401,170 blobs. Step 2 regenerates them.
        { "abc@example.com", "2026-03-20T21:52:57Z", "k5e610767040b7fc3c8b636" },
        { "ABC@Example.COM", "2026-03-20T21:52:57Z", "k5e610767040b7fc3c8b636" },
        { "DS0PR10MB7361@DS0PR10MB7361.prod.com", "2025-09-22T23:36:06Z", "k6031a596c24c60cb439873" },
        { "a+b/c=d@example.com", "2024-01-01T00:00:00Z", "kb7cd42df10cc39613703fe" },
    };

    [Theory]
    [MemberData(nameof(Reference))]
    public void Csharp_reproduces_the_python_token(string mid, string sent, string expected)
    {
        Assert.Equal(expected, DedupToken.Key(mid, sent));
    }
}
